services:
  goexpert-lab-deploy-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - WEATHER_SECRET_KEY=${WEATHER_SECRET_KEY}
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/tmp
    restart: unless-stopped

